export enum AUTH_SUCCESS {
  ACCOUNT_CREATION = 'Your account has been successfully created. Please check your email address for the otp.',
  GOOGLE_ACCOUNT_CREATION = 'Your account has been successfully created.',
  ACCOUNT_LOGIN = 'Your account has been logged in successfully.',
  FORGOT_PASSWORD = 'The password reset email has been sent successfully.',
  RESET_PASSWORD = 'Your password has been reset successfully. Please log in with your new password.',
  VALID_TOKEN = 'Successfully validate the token.',
  VALID_OTP = 'OTP verification successful',
  OTP_SENT = 'OTP send successfully',
  LOGIN_SUCCESSFULLY = 'Sign in successful',
  SESSIONS_RETRIEVED = 'User sessions retrieved successfully',
  SIGNED_OUT_OTHER_DEVICES = 'Successfully signed out from other devices',
  CHANGE_PASSWORD = 'Password changed successfully',
  ALL_SESSIONS_INVALIDATED = 'All sessions invalidated successfully',
  USER_FOUND = 'Successfully found user',
  ACCOUNT_DELETED = 'Account deleted successfully',
}

export enum AUTH_ERRORS {
  INVALID_CURRENT_PASSWORD = 'Invalid current password',
  INCORRECT_CREDENTIALS = 'Incorrect email or password.',
  USER_NOT_FOUND = 'Unable to find the user.',
  DUPLICATE_EMAIL = 'User with same email already exist.',
  ACCOUNT_CREATION = 'An error occurred while creating new user.',
  ACCOUNT_LOGIN = 'An error occurred while logging the account.',
  UNAUTHORIZED = 'You are not authorized to access this operation.',
  UNAUTENTICATED = 'You are not authenticated to access this operation',
  FORGOT_PASSWORD = 'An error occurred while resetting user password.',
  INVALID_TOKEN = 'Your token is not validated.',
  INVALID_OTP = 'Invalid OTP.',
  RESET_TOKEN_VALIDATION = 'Your token is not validated or has been expired.',
  EMAIL_NOT_VERIFIED = 'Your email is not verified.',
  EMAIL_ALREADY_VERIFIED = 'Email already verified',
  OTP_EXPIRED = 'Your otp is expired.',
  USER_EXIST_WITH_OTHER_PROVIDER = 'An account with these credentials already exists with a different provider.',
  ERROR_SOCIAL_LOGIN_PASSWORD_RESET = "We can't reset your password because this account uses Google SignIn. Please click Continue with Google to log in.",
  'USER_SESSION_NOT_FOUND' = 'User session not found',
  NEW_PASSWORD_SAME_AS_CURRENT = 'New password cannot be the same as your current password.',
}
