export enum PAYPAL_SUCCESS {
  ORDER_CREATED = 'PayPal order created successfully',
  ORDER_RETRIEVED = 'PayPal order retrieved successfully',
  ORDER_CAPTURED = 'PayPal order captured successfully',
  SESSION_VERIFIED = 'PayPal checkout session verified successfully',
  SUBSCRIPTION_CREATED = 'PayPal subscription created successfully',
  SUBSCRIPTION_RETRIEVED = 'PayPal subscription retrieved successfully',
  SUBSCRIPTIONS_RETRIEVED = 'PayPal subscriptions retrieved successfully',
  SUBSCRIPTION_UPDATED = 'PayPal subscription updated successfully',
  SUBSCRIPTION_CANCELED = 'PayPal subscription canceled successfully',
  SUBSCRIPTION_ACTIVATED = 'PayPal subscription activated successfully',
  SUBSCRIPTION_SUSPENDED = 'PayPal subscription suspended successfully',
  SUBSCRIPTION_RESUMED = 'PayPal subscription resumed successfully',
  INVOICE_CREATED = 'PayPal invoice created successfully',
  INVOICE_RETRIEVED = 'PayPal invoice retrieved successfully',
  INVOICE_PAYMENT_RECORDED = 'PayPal invoice payment recorded successfully',
  WEBHOOK_VERIFIED = 'PayPal webhook verified successfully',
}

export enum PAYPAL_ERRORS {
  ORDER_CREATION_FAILED = 'Failed to create PayPal order',
  ORDER_RETRIEVAL_FAILED = 'Failed to retrieve PayPal order',
  ORDER_CAPTURE_FAILED = 'Failed to capture PayPal order',
  SESSION_VERIFICATION_FAILED = 'Failed to verify PayPal checkout session',
  SUBSCRIPTION_CREATION_FAILED = 'Failed to create PayPal subscription',
  SUBSCRIPTION_NOT_FOUND = 'PayPal subscription not found',
  SUBSCRIPTION_RETRIEVAL_FAILED = 'Failed to retrieve PayPal subscription',
  SUBSCRIPTION_CANCELLATION_FAILED = 'Failed to cancel PayPal subscription',
  SUBSCRIPTION_ACTIVATION_FAILED = 'Failed to activate PayPal subscription',
  SUBSCRIPTION_SUSPEND_FAILED = 'Failed to suspend PayPal subscription',
  PLAN_NOT_FOUND = 'PayPal plan not found',
  FEATURE_NOT_SUPPORTED = 'This PayPal feature is not supported',
  INVOICE_CREATION_FAILED = 'Failed to create PayPal invoice',
  INVOICE_RETRIEVAL_FAILED = 'Failed to retrieve PayPal invoice',
  INVOICE_PAYMENT_FAILED = 'Failed to record PayPal invoice payment',
  CUSTOMER_NOT_FOUND = 'PayPal payer not found',
  WEBHOOK_VERIFICATION_FAILED = 'Failed to verify PayPal webhook signature',
  WEBHOOK_PROCESSING_FAILED = 'Failed to process PayPal webhook event',
  CONFIGURATION_ERROR = 'PayPal configuration is invalid',
  API_ERROR = 'Unexpected error from PayPal API',
}

