export enum STRIPE_SUCCESS {
  CARD_ADDED = 'Card added successfully',
  CARD_DELETED = 'Card deleted successfully',
  CARD_SET_DEFAULT = 'Card set as default successfully',
  CARDS_RETRIEVED = 'Cards retrieved successfully',
  ALL_CARDS_RETRIEVED = 'All cards retrieved successfully',
  PAYMENT_METHOD_ATTACHED = 'Payment method attached successfully',
  PAYMENT_METHOD_DETACHED = 'Payment method detached successfully',
  CUSTOMER_UPDATED = 'Customer updated successfully',
  INVOICES_RETRIEVED = 'Invoices retrieved successfully',
  INVOICE_CREATED = 'Invoice created successfully',
  INVOICE_RETRIEVED = 'Invoice retrieved successfully',
  INVOICE_PAID = 'Invoice paid successfully',
  INVOICE_FINALIZED = 'Invoice finalized successfully',
  PAYMENT_INTENT_CREATED = 'Payment intent created successfully',
  PAYMENT_INTENT_RETRIEVED = 'Payment intent retrieved successfully',
  CHECKOUT_SESSION_CREATED = 'Checkout session created successfully',
  SESSION_VERIFIED = 'Session verified successfully',
  PAYMENT_SUCCEEDED = 'Payment completed successfully',
}

export enum STRIPE_ERRORS {
  CARD_NOT_FOUND = 'Card not found',
  PAYMENT_METHOD_NOT_FOUND = 'Payment method not found',
  CUSTOMER_NOT_FOUND = 'Customer not found',
  PAYMENT_METHOD_ATTACHMENT_FAILED = 'Failed to attach payment method',
  PAYMENT_METHOD_DETACHMENT_FAILED = 'Failed to detach payment method',
  CUSTOMER_UPDATE_FAILED = 'Failed to update customer',
  STRIPE_API_ERROR = 'Stripe API error occurred',
  INVALID_PAYMENT_METHOD = 'Invalid payment method',
  PAYMENT_METHOD_ALREADY_ATTACHED = 'Payment method is already attached to this customer',
  PAYMENT_METHOD_NOT_ATTACHED = 'Payment method is not attached to any customer',
  CUSTOMER_ID_REQUIRED = 'Customer ID is required',
  PAYMENT_METHOD_ID_REQUIRED = 'Payment method ID is required',
  DUPLICATE_CARD = 'A card with the same fingerprint already exists',
  WEBHOOK_SIGNATURE_VERIFICATION_FAILED = 'Webhook signature verification failed',
  WEBHOOK_PROCESSING_FAILED = 'Webhook processing failed',
  INVOICE_CREATION_FAILED = 'Failed to create invoice',
  INVALID_DATE_RANGE = 'Invalid date range - start date must be before end date',
  INVOICE_NOT_FOUND = 'Invoice not found',
  INVOICE_PAYMENT_FAILED = 'Failed to pay invoice',
  INVOICE_ALREADY_PAID = 'Invoice is already paid',
  INVOICE_NOT_FINALIZED = 'Invoice is not in open status',
  INVOICE_FINALIZATION_FAILED = 'Failed to finalize invoice',
  PAYMENT_INTENT_CREATION_FAILED = 'Failed to create payment intent',
  CHECKOUT_SESSION_CREATION_FAILED = 'Failed to create checkout session',
  PAYMENT_INTENT_NOT_FOUND = 'Payment intent not found',
  SESSION_NOT_FOUND = 'Checkout session not found',
  GUEST_EMAIL_REQUIRED = 'Guest email is required for unauthenticated payments',
  INVALID_AMOUNT = 'Amount must be at least 50 cents',
}
